### ISSUE TITLE
issues with encryption layout

### ISSUE THREAD

**Issue by IslaIDK** [Praudyogikee-org/Anonybox#5]
python version should use asymmetric aside with symmetric. the app starts connection with users with no encryption that allow attackers to guess the stages and extract the data or even spoof it, how to fix it ? force the users to use asymmetric encryption when they started the connection also change the login method it's not a good way just mix them all in one.

**Comment by qarqoush** [comment]
Greetings,
This is considered as A vulnerability, As it affects users' security and privacy.
We're planning to implement diffie-hellman algorithm for encryption key. Currently, All Python / Java Versions are out-dated due to old and/or insecure technology.

Also, Anonybox's happy if you're contributing to this project to fix this issue and/or vulnerability, as there's NO python developers are in work at the moment.
The next update is for java version, as it brings new technologies and a different API, Anonybox will consider your issue and fix it in the java version "if this issue exists".
Thanks for your submission, Efforts are highly appreciated..


[ If you have any comment, please contact morad.gill@gmail.com with ticket number #0003 ]
